db:
  image: mdillon/postgis:9.4
  volumes:
  - ./initdb-postgis.sh:/docker-entrypoint-initdb.d/postgis.sh
  # NOTE: the following mount is commented out because it fails on Mac OS X.
  # The error can be fixed by running initdb manually on that directory by the host.
  # - /usr/local/var/postgres:/var/lib/postgresql/data
  ports:
  - "5432"

ourd:
  image: oursky/ourd:master
  ports:
  - "3000:3000"
  - "5555"
  volumes:
  - ./development.ini:/go/src/app/config.ini
  - ./data:/var/lib/ourd/data
  links:
  - db
  command: sh -c "PGHOST=db PGPORT=$DB_PORT_5432_TCP_PORT $GOPATH/bin/ourd config.ini"
  environment:
    DATABASE_URL: dbname=postgres sslmode=disable
    PGUSER: postgres

# sample python plugin configuration
# pyourd:
#   image: oursky/pyourd:onbuild
#   links:
#   - ourd
#   - db
#   # mount your python sources here
#   volumes:
#   - ./python/plugin.py:/usr/src/app/plugin.py
#   # run the mounted python entrypoint via pyourd here
#   command: sh -c "pyourd plugin.py --ourd-address=tcp://ourd:$OURD_PORT_5555_TCP_PORT"
